In [11]:
import numpy as np 

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
a = np.array([1, 2, 3, 4, 5], ndmin=2)
a

array([[1, 2, 3, 4, 5]])

In [10]:
a = np.array([1, 2, 3], dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# 정수형 

In [12]:
import numpy as np 
dt = np.dtype(np.int32)
print(dt)

int32


In [13]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
print(dt)

int32
