In [2]:
import numpy as np

strarr = np.array(list('Python'))
print(strarr[0], strarr[-6])
print(strarr[1], strarr[-5])
print(strarr[2], strarr[-4])
print(strarr[3], strarr[-3])
print(strarr[4], strarr[-2])
print(strarr[5], strarr[-1])


P P
y y
t t
h h
o o
n n


In [3]:
import numpy as np 

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# 인덱스 행 가져오기. 
print(arr2d[1])

[4 5 6]


In [5]:
# 특정 행들만 선택해서 가져오기 
# 첫번재 행과 마지막 행 가져오기. 
print(arr2d[(0, -1), :])

[[ 1  2  3]
 [10 11 12]]


In [6]:
# 행열의 인덱스 가져오기 
# 첫번째 행 두번째 열 데이터 가져오기 (2) 
print(arr2d[0][1])

2


In [19]:
# 특정 열 전체 가져오기. 
# 3번째 열 전체 가져오기. 
print(arr2d[...,2])
print(arr2d[:,2])

[3 6 9]
[3 6 9]


In [8]:
# 두번째열부터 전체 가져오기 
print(arr2d[...,1:])

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


In [9]:
# 필요한 열들만 선택해서 가져오기 
# 첫번째열, 마지막열만 가져오기 
print(arr2d[...,(0,-1)])

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [10]:
# 두번째, 세번째 행의 첫번째, 마지막 열만 가져오기. 
print(arr2d[1:3, (0,-1)])

[[4 6]
 [7 9]]


In [11]:
# 첫번째, 마지막 행의, 첫번째, 마지막 열만 가져오기. 
print(arr2d[...,(0,-1)][(0, -1),...])

[[ 1  3]
 [10 12]]


In [12]:
## Slicing
import numpy as np

In [13]:
## 1차원 배열 
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1[2:])

[3 4 5 6 7 8 9]


In [14]:
print(arr1[2:-1])

[3 4 5 6 7 8]


In [15]:
## 2차원 배열 생성하기. 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
## 행 슬라이싱 
print(arr2d[1:2, :])

[[4 5 6]]


In [17]:
print(arr2d[1:3, :])

[[4 5 6]
 [7 8 9]]


In [18]:
print(arr2d[1:3, 2:])

[[6]
 [9]]
