In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
print(a.shape)

(2, 3)


In [3]:
# resize 
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# reshape function 
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
# 배열 목록 생성 
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
# 배쳘 차원 확인 및 차원 확인하기. 
a = np.arange(24)
print(a.ndim)

1


In [8]:
b = a.reshape(2, 4, 3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [11]:
# numpy.itemsize 확인, 각 요소 길이를 바이트 단위로 반환 
x = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(x.itemsize)

1


In [12]:
# 배열의 타입을 다른 타입으로 변경 한다. 
x = np.array([1, 2, 3, 4, 5], dtype = np.float32)
print(x.itemsize)

4


In [14]:
# 배열 생성 루틴 확인하기. 
# numpy.empty(shape, dtype = float, order = 'C')

In [16]:
import numpy as np 
x = np.empty([3, 2], dtype = int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
# 0값으로 채워진 배열 생성 
x = np.zeros([2, 3], dtype = int)
print(x)

[[0 0 0]
 [0 0 0]]


In [19]:
# 0부동소숫점으로 배열 생성 
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [20]:
x = np.zeros(5, dtype=int)
print(x)

[0 0 0 0 0]


In [23]:
# custom type 으로 배열 생성하기. 
x = np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [24]:
# 1값으로 채워진 배열 생성 
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [25]:
x = np.ones(5, dtype = int)
print(x)

[1 1 1 1 1]
