In [2]:
import numpy as np

In [4]:
# 1차원 배열의 shape 
addr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(addr1.shape)

(9,)


In [8]:
# 2차원 배열의 shape 
addr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(addr2d)
print(addr2d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [13]:
addr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(addr3d)
print(addr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [15]:
# 1차원 배열의 길이 총 9개의 데이터가 들어있다. 
print(len(addr1))

9


In [18]:
# 2차원 배열의 길이 총 4개의 row가 존재한다. 
print(len(addr2d))

# 2차원 배열 행의 len 구하기. 총 3개의 데이터가 존재함을 알 수 있다. 
print(len(addr2d[0]))

4
3


In [23]:
# 1차원 배열의 ndim 
print(addr1.ndim)

1


In [24]:
# 2차원 배열의 ndim
print(addr2d.ndim)

2


In [25]:
# 3차원 배열의 ndim
print(addr3d.ndim)

3


In [27]:
# str타입으로 데이터 형변환하기. 
str_addr1 = addr1.astype('str')
print(str_addr1)

['1' '2' '3' '4' '5' '6' '7' '8' '9']


In [28]:
# 다시 str타입을 float타입으로 변경하기. 
print(str_addr1.astype('float'))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [30]:
# 데이터 타입의 변화 확인하기. 
# 원본 데이터 타입 
print(addr1.dtype)

# str로 형변환 후 데이터 타입
str_addr1 = addr1.astype('str')
print(str_addr1.dtype)

# str -> float 로 형변환 후 데이터 타입
float_addr1 = str_addr1.astype('float')
print(float_addr1.dtype)


int64
<U21
float64


In [32]:
# 1차원 배열의 size 
print(addr1.size)

# 2차원 배열 4 * 3의 size
print(addr2d.size)

# 3차원 배열 2 * 2 * 3의 size
print(addr3d.size)

9
12
12
