In [1]:
# 파이썬 리스트를 ndarray로 변경하기. 
import numpy as np 
x = [1, 2, 3]
a = np.asarray(x)
print(a)

[1 2 3]


In [2]:
# 타입 지정하여 배열생성하기. 
a = np.asarray(x, dtype = float)
print(a)

[1. 2. 3.]


In [3]:
# 투플을 배열로 생성하기. 
x = (1, 2, 3)
a = np.asarray(x)
print(a)

[1 2 3]


In [4]:
# 튜플의 리스트로 배열 생성하기. 
x = [(1, 2, 3), (4, 5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


/var/folders/7w/k23qswcd04z8925pqjt296rw0000gp/T/ipykernel_89089/2591114892.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.asarray(x)


In [13]:
# 범위 이용하여 배열 생성 
# numpy.arange(start, stop, step, dtype)
# start: 시작값, stop: 종료값, step: 증분, dtype: 데이터 타입 
import numpy as np
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [14]:
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [15]:
x = np.arange(10, 20, 2)
print(x)

[10 12 14 16 18]


In [16]:
# linspace로 배열 생성하기. 
# linspace는 arange 함수와 유사, step size 대신에 지정된 범위 사이를 고정 분할로 데이터를 채움 
# numpy.linspace(start, stop, num, endpoint, retstep, dtype)
# start: 시퀀스의 시작값 
# stop:  시퀀스의 종료값, 만약 endpoint가 True로 설정되면 종료값이 포함된다. 
# num: 생성할 균등 샘플링 수, 기본값은 50이다. 
# endpoint: 기본값은 True이며, 종료값이 시퀀스에 포함될지 여부이다. 만약 False로 설정하면 종료값은 포함되지 않는다. 
# retstep: 만약 True로 설정하면 샘플을 반환하고, 연속된 숫자 사이의 단계를 수행한다. 
# dtype: 데이터 타입 

x = np.linspace(10, 20, 5) # 10, 20 사이 값으로 5개의 균등값을 찾아낸다. 
print(x)

[10.  12.5 15.  17.5 20. ]


In [17]:
# endpoint 값이 False인경우 
x = np.linspace(10, 20, 5, endpoint = False)
print(x)

[10. 12. 14. 16. 18.]


In [19]:
# 다음은 1 ~ 2 사이의 값으로 5개의 균등값을 반환한다. 균등값의 스텝값 역시 반환하며 여기서는 0.25가 된다. 
x = np.linspace(1, 2, 5, retstep = True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [20]:
# numpy.logspace 
# 배열 값을 생성하며, 이때 균등한 값의 개수를 출력하지만 로그 스케일로 균등값을 출력한다. 
# numpy.logspace(start, stop, num, endpoint, base, dtype) 
# start: 시작범위 
# stop: 종료범위 
# num: 균등값을 추출할 값의 개수 
# endpoint: True인경우 종료값 포함, False인경우 종료값 미 포함 
# base: 로그 값의 베이스, 기본값은 10이다. 
# dtype: 데이터 타입 

import numpy as np 
a = np.logspace(1.0, 2.0, num = 10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [21]:
a = np.logspace(1, 10, num = 10, base = 2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
