In [2]:
import numpy as np

In [3]:
# 배열 생성
arr01 = np.array([1, 2, 3])
arr02 = np.array([9, 8, 7])
print(arr01, arr02)

[1 2 3] [9 8 7]


In [6]:
## 덧셈 연산 
arr_sum = arr01 + arr02
print(arr_sum)

[10 10 10]


In [7]:
## 뺄셈 연산 
arr_sub = arr02 - arr01
print(arr_sub)

[8 6 4]


In [8]:
## 곱셈 연산 
arr_mul = arr01 * arr02
print(arr_mul)

[ 9 16 21]


In [9]:
## 나숫셈 연산 
arr_div = arr01 / arr02
print(arr_div)

[0.11111111 0.25       0.42857143]


In [11]:
## mod 연산 
arr_mod = arr02 % arr01
print(arr_mod)

[0 0 1]


In [6]:
# Sclar 연산 
arr_sclar = arr01 * 10
print(arr_sclar)

[10 20 30]


In [7]:
# 1차원 배열의 행열 연산 
dot_prod_1d = np.dot(arr01, arr02)
print(dot_prod_1d)

46


In [9]:
# 2차원 배열의 dot product 
arr2d01 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d01)

arr2d02 = np.array([[1, 1], [2, 2], [3, 3]])
print(arr2d02)

dot_prod_2d = np.dot(arr2d01, arr2d02)
print(dot_prod_2d)

[[1 2 3]
 [4 5 6]]
[[1 1]
 [2 2]
 [3 3]]
[[14 14]
 [32 32]]


In [6]:
# np.add
print(np.add(arr01, arr02))

# np.subtract
print(np.subtract(arr02, arr01))

# np.multiply
print(np.multiply(arr01, arr02))

# np.divide
print(np.divide(arr02, arr01))

# np.mod
print(np.mod(arr01, arr02))

[10 10 10]
[8 6 4]
[ 9 16 21]
[9.         4.         2.33333333]
[1 2 3]
