In [4]:
import numpy as np 

a = np.arange(10)
s = slice(2, 7, 2)
print(a)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [6]:
# ndarray 객체의 내용을 접근할 수 있으며, 인덱싱을 이용하여 변경하거나, 슬리이싱 할 수 있다. 
# ndarray 내부에 아이텤들은 0 인덱스부터 시작이다. 
# 인덱싱 방법은 3가지가 가능하다. 
# - field 접근, 슬라이싱, 고급 인덱싱 
# 기본 슬라이싱은 n차원으로 슬라이싱 하는 Python의 기본 개념을 확장한다. 
# Python 슬리이스 객체는 start, stop, step 파라미터를 이용할 수 있다. 
import numpy as np 
a = np.arange(10)
s = slice(2, 7, 2) # 시작, 종료, 스텝 
print(a[s]) # [2, 4, 6]

[2 4 6]


In [ ]:
# 위 예제는 ndarray객체가 aragne() 함수로 생성된 것이다. 
# 그리고 slice 객체는 start, stop, step 으로 구성되어 있다. 

In [7]:
# 슬라이싱 방법 2
# [start:stop:step] 형태로 조회할 수 있다. 
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [8]:
a = np.arange(10)
b = a[5]
print(b)

5


In [10]:
a = np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [11]:
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [12]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [13]:
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [14]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [16]:
# 2번째 칼럼에서 아이텤들을 출력한다. 
print(a[...,1])

[2 4 5]


In [17]:
# 두번재 행의 전체 아이템을 출력한다. 
print(a[1,...])

[3 4 5]


In [18]:
# 1칼럼 이후의 모든 칼럼을 출력한다.
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


[0 1 2 3 4 5 6 7 8 9]
