In [2]:
import numpy as np


In [3]:
arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 합계 구하기. 
print(np.sum(arr1d))

55


In [4]:
# 최소값 
print(np.min(arr1d))

0


In [5]:
# 배열 원소의 최대값 구하기. 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.max(arr2d))

9


In [6]:
# 행 기준으로 최대값을 구하기
print(np.max(arr2d, axis=1))

[3 6 9]


In [7]:
# 열 기준으로 최대값 구하기.
print(np.max(arr2d, axis=0))

[7 8 9]


In [9]:
# cumsum() 으로 배열의 누적값 구하기. 
print(np.cumsum(arr1d))

[ 0  1  3  6 10 15 21 28 36 45 55]


In [10]:
# cumsum() 으로 2차원 배열 누적값 구하기. 
print(np.cumsum(arr2d))

[ 1  3  6 10 15 21 28 36 45]


In [11]:
# 행 기준으로 누적값 구하기. 
print(np.cumsum(arr2d, axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [12]:
# 열 기준으로 누적값 구하기 
print(np.cumsum(arr2d, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [13]:
# 평균 구하기. 
print(np.mean(arr1d))

5.0


In [15]:
# 행 기준 평균값 
print(np.mean(arr2d, axis=1))

[2. 5. 8.]


In [16]:
# 열 기준 평균값 
print(np.mean(arr2d, axis=0))

[4. 5. 6.]


In [17]:
# 중간값 구하기 
print(np.median(arr1d))

5.0


In [18]:
# 2차원 배열 중간값 구하기 
print(np.median(arr2d))

5.0


In [19]:
# 행기준 중간값 
print(np.median(arr2d, axis=1))

[2. 5. 8.]


In [20]:
# 열 기준 중간값 
print(np.median(arr2d, axis=0))

[4. 5. 6.]


In [25]:
arr2d_another = np.array([[1, 3, 2], [8, 16, 4], [15, 10, 12]])
print(np.median(arr2d_another))
# [1, 2, 3, 4, 8, 10, 16, 12, 16] --> 에서 중간값인 8이 출력된다. 즉, sort되어서 출력된다. 

8.0


In [26]:
print(np.median(arr2d_another, axis=1))

[ 2.  8. 12.]


In [ ]:
prin