In [2]:
import numpy as np

In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# reshape 로 배열 형태 변경하기 (4, 3) --> (3, 4)로 변경 
arr2d_reshape = arr2d.reshape(3, 4)
print(arr2d_reshape)
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# resize 로 배열 형태 변경하기. 
arr2d_resize = arr2d.resize(3, 4)
print(arr2d_resize)
print(arr2d)

None
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# append 로 배열 원소 추가 
arr1d = np.array([1, 2, 3])
print(arr1d)

[1 2 3]


In [17]:
# 배열에 상수값 추가하기. 
arr1d_append_scalar = np.append(arr1d, 10)
print(arr1d)
print(arr1d_append_scalar)

[1 2 3]
[ 1  2  3 10]


In [18]:
# 배열에 배열 추가하기. 
arr1d_append_array = np.append(arr1d, [10, 20, 30])
print(arr1d_append_array)

[ 1  2  3 10 20 30]


In [23]:
# append 2dim
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
apparr1d = np.array([7, 8, 9])

new_arr2d = np.append(arr2d, apparr1d)
print(new_arr2d)

[1 2 3 4 5 6 7 8 9]


In [20]:
# 배열 행으로 추가하기. 
new_arr2d_row = np.append(arr2d, apparr1d, axis=1)
print(new_arr2d_row)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [26]:
# 배열 행으로 추가 재시도 2차원 배열 (axis = 0 이면 열방향 --> 즉 아래 행으로 추가된다.)
apparr2d = np.array([[7, 8, 9]])
new_arr2d_row = np.append(arr2d, apparr2d, axis=0)
print(new_arr2d_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# 배열 열로 추가하기. 
print(arr2d)
appear2d = np.array([[5],[7]])
new_arr2d_col = np.append(arr2d, appear2d,axis = 1)
print(new_arr2d_col)


[[1 2 3]
 [4 5 6]]
[[1 2 3 5]
 [4 5 6 7]]


In [40]:
# insert 로 배열 원소 추가하기. (1번째 인덱스에 10 추가하기)
arr1d = np.array([1, 2, 3])
arr1d_inserted = np.insert(arr1d, 1, 10)
print(arr1d)
print(arr1d_inserted)

[1 2 3]
[ 1 10  2  3]


In [49]:
# 행으로 추가하기. 
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d_inserted = np.insert(arr2d, 1, [7, 8, 9], axis = 0)
print(arr2d_inserted)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [51]:
# 배열 추가하기. 
arr2d_inserted_col = np.insert(arr2d, 1, [10, 20])
print(arr2d_inserted_col)

[ 1 10 20  2  3  4  5  6]


In [53]:
# 열로 추가하기. 
arr2d_inserted_col = np.insert(arr2d, 1, [10, 20], axis = 1)
print(arr2d_inserted_col)

[[ 1 10  2  3]
 [ 4 20  5  6]]


In [48]:
# 열로 추가하기. 
arr2d_inserted_col = np.insert(arr2d, 1, [[10], [20]], axis = 1)
print(arr2d_inserted_col)

[[ 1 10 20  2  3]
 [ 4 10 20  5  6]]


In [56]:
# 열로 추가하기. 
arr2d_inserted_col = np.insert(arr2d, 1, [10, 20, 30], axis = 1)
print(arr2d_inserted_col)

ValueError: could not broadcast input array from shape (3,1) into shape (2,1)

In [62]:
# 배열 개체 삭제하기. 
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
deleted_arr1d = np.delete(arr1d, 9)
print(arr1d)
print(deleted_arr1d)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]


In [63]:
# 한꺼번에 여러 배열 제거하기. (튜플이용)
deleted_arr1d_multi = np.delete(arr1d, (1, 5, 9))
print(deleted_arr1d_multi)

[1 3 4 5 7 8 9]


In [64]:
# 한꺼번에 여러 배열 제거하기, (배열이용)
deleted_arr1d_multi = np.delete(arr1d, [1, 5, 9])
print(deleted_arr1d_multi)

[1 3 4 5 7 8 9]


In [65]:
# 2차원 배열 제거 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
deleted_arr2d = np.delete(arr2d, 1)
print(deleted_arr2d)

[1 3 4 5 6 7 8 9]


In [67]:
# 2차원 배열 제거 (행제거)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
deleted_arr2d = np.delete(arr2d, 1, axis = 0)
print(deleted_arr2d)

[[1 2 3]
 [7 8 9]]


In [68]:
# 2차원 배열 제거 (열제거)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
deleted_arr2d = np.delete(arr2d, 1, axis = 1)
print(deleted_arr2d)

[[1 3]
 [4 6]
 [7 9]]


In [69]:
# transpose() 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tranposed_arr2d = np.transpose(arr2d)
print(arr2d)
print(tranposed_arr2d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [70]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tranposed_arr2d = arr2d.T
print(arr2d)
print(tranposed_arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
