In [2]:
import numpy as np

In [4]:
addr1d = np.array([1, 2, 3])
newarr = addr1d * 2
print(newarr)

[2 4 6]


In [5]:
# 2차원 배열과 1차원 배열의 broadcasting
arr2d = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
arr1d = np.array([1, 2, 3])

added_arr = arr2d + arr1d 
print(added_arr)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [6]:
# 브로드캐스팅 오류 
arr2d = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
arr1d = np.array([1, 2, 3, 4])

added_arr = arr2d + arr1d 
print(added_arr)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [8]:
# 행만 존재하는 2차원 배열과 1차원 배열의 브로드캐스팅
arr2d_just_1columns = np.array([[0], [10], [20], [30]])
print(arr2d_just_1columns)
arr1d = np.array([1, 2, 3])
print(arr1d)
new_array = arr2d_just_1columns + arr1d 
print(new_array)

[[ 0]
 [10]
 [20]
 [30]]
[1 2 3]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [9]:
# np.newaxis 를 이용하여 배열 2차원 배열 생성후 브로드캐스팅 
arr1d_01 = np.array([0, 10, 20, 30])
arr1d_02 = np.array([1, 2, 3])
new_array = arr1d_01[:, np.newaxis] + arr1d_02

print(new_array)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
